# Dataset analysis

In [2]:
import pandas as pd
import numpy as np
import os
import utils

In [3]:
features_1 = [
    'sx_roll',
    'sx_pitch',
    'sx_yaw',
    'sx_thumb',
    'sx_x',
    'sx_y',
    'sx_z',
    'sx_forefinger',
    'sx_middle_finger',
    'sx_ring_finger',
    'sx_little_finger',
    'dx_roll',
    'dx_pitch',
    'dx_yaw',
    'dx_x',
    'dx_y',
    'dx_z',
    'dx_thumb',
    'dx_forefinger',
    'dx_middle_finger',
    'dx_ring_finger',
    'dx_little_finger'
    ]



In [4]:
path = "../../Desktop/MML Project/tctodd/"
dirs = os.listdir(path=path)
weeks = sorted([i for i in dirs if i != ".DS_Store"])
filenames = sorted(os.listdir(path+weeks[1]))

data = []
labels = dict()
label_cnt = 0

for w in weeks:
    temp_path = path+w+"/"
    filenames = sorted(os.listdir(temp_path))
    for fn in filenames:
        label = fn.split('.')[0][:-2]
        
        if label not in labels:
            labels[label] = label_cnt
            label_cnt += 1
            
        data.append({'label':labels[label], 'time_series':pd.read_csv(temp_path+fn, header=None, sep='\t',).values})
        

Had to change her label in tctodd1 in his_hers. Otherwise 96 labels instead of 95.
vedere se le varie label di his_hers sono statisticamente simili (che vuol dire statisticamente? boh guardiamo media e dev. std)

In [5]:
df = pd.DataFrame(data, columns=['label', 'time_series'])
print(df['label'].value_counts())
df.head()

0     27
60    27
69    27
68    27
67    27
      ..
29    27
28    27
27    27
26    27
94    27
Name: label, Length: 95, dtype: int64


label                                        time_series
0      0  [[-0.064909, 0.034318, -0.043964, 0.626383, 0....
1      0  [[-0.107059, -0.126109, -0.053742, 0.612516, 0...
2      0  [[-0.061427, -0.082576, -0.102991, 0.735469, 0...
3      1  [[-0.128178, 0.02695, -0.050126, 0.455028, 0.4...
4      1  [[-0.143672, -0.144416, -0.047447, 0.660979, 0...

In [6]:
np.mean(df['time_series'].iloc[0], axis=0)

array([-0.12359908,  0.02004841, -0.04530714,  0.47213429,  0.53506589,
        0.49491324,  0.17544914,  0.19811941,  0.17947179,  0.20405468,
        0.21601179,  0.07842527,  0.06782231, -0.03748164,  0.38855008,
        0.5130405 ,  0.55184169,  0.19595423,  0.05150761,  0.18715093,
        0.1726928 ,  0.33196956])

In [6]:
lengths = []
for i in range(len(df)):
    lengths.append(df.iloc[i]['time_series'].shape[0])
print(np.mean(lengths))

57.29005847953216


In [7]:
df['time_series'].iloc[0]

array([[-0.064909,  0.034318, -0.043964, ...,  1.      ,  0.754117,
         1.      ],
       [-0.033878,  0.034764, -0.032445, ...,  1.      ,  0.97451 ,
         1.      ],
       [ 0.015014,  0.030924, -0.012665, ...,  1.      ,  1.      ,
         1.      ],
       ...,
       [-0.158942,  0.009224, -0.057761, ...,  0.      ,  0.      ,
         0.172542],
       [-0.162514,  0.00717 , -0.05785 , ...,  0.      ,  0.      ,
         0.172542],
       [-0.163496,  0.006947, -0.058029, ...,  0.      ,  0.      ,
         0.172542]])

In [6]:
import sklearn as sk
from sklearn.model_selection import train_test_split
seed = 0

# Shuffle the dataframe
shuffled_df = sk.utils.shuffle(df, random_state=seed)
X_train, X_test, y_train, y_test = train_test_split(shuffled_df['time_series'], shuffled_df['label'], stratify=shuffled_df['label'],  train_size=.9, random_state=seed)

In [9]:
unique, counts = np.unique(y_train.values, return_counts=True)
print(np.asarray((unique, counts)).T)

[[ 0 24]
 [ 1 24]
 [ 2 25]
 [ 3 24]
 [ 4 24]
 [ 5 24]
 [ 6 25]
 [ 7 25]
 [ 8 25]
 [ 9 24]
 [10 24]
 [11 24]
 [12 24]
 [13 25]
 [14 24]
 [15 24]
 [16 25]
 [17 24]
 [18 24]
 [19 24]
 [20 24]
 [21 24]
 [22 25]
 [23 24]
 [24 25]
 [25 24]
 [26 25]
 [27 24]
 [28 24]
 [29 24]
 [30 25]
 [31 24]
 [32 24]
 [33 25]
 [34 24]
 [35 24]
 [36 24]
 [37 24]
 [38 24]
 [39 24]
 [40 24]
 [41 24]
 [42 25]
 [43 25]
 [44 24]
 [45 25]
 [46 24]
 [47 24]
 [48 25]
 [49 24]
 [50 24]
 [51 25]
 [52 24]
 [53 24]
 [54 24]
 [55 24]
 [56 25]
 [57 24]
 [58 24]
 [59 24]
 [60 25]
 [61 25]
 [62 25]
 [63 24]
 [64 24]
 [65 24]
 [66 24]
 [67 24]
 [68 24]
 [69 24]
 [70 24]
 [71 24]
 [72 24]
 [73 25]
 [74 25]
 [75 24]
 [76 25]
 [77 24]
 [78 24]
 [79 25]
 [80 25]
 [81 24]
 [82 24]
 [83 24]
 [84 24]
 [85 24]
 [86 24]
 [87 24]
 [88 25]
 [89 24]
 [90 25]
 [91 24]
 [92 24]
 [93 24]
 [94 25]]


In [10]:
unique, counts = np.unique(y_test.values, return_counts=True)
print(np.asarray((unique, counts)).T)

[[ 0  3]
 [ 1  3]
 [ 2  2]
 [ 3  3]
 [ 4  3]
 [ 5  3]
 [ 6  2]
 [ 7  2]
 [ 8  2]
 [ 9  3]
 [10  3]
 [11  3]
 [12  3]
 [13  2]
 [14  3]
 [15  3]
 [16  2]
 [17  3]
 [18  3]
 [19  3]
 [20  3]
 [21  3]
 [22  2]
 [23  3]
 [24  2]
 [25  3]
 [26  2]
 [27  3]
 [28  3]
 [29  3]
 [30  2]
 [31  3]
 [32  3]
 [33  2]
 [34  3]
 [35  3]
 [36  3]
 [37  3]
 [38  3]
 [39  3]
 [40  3]
 [41  3]
 [42  2]
 [43  2]
 [44  3]
 [45  2]
 [46  3]
 [47  3]
 [48  2]
 [49  3]
 [50  3]
 [51  2]
 [52  3]
 [53  3]
 [54  3]
 [55  3]
 [56  2]
 [57  3]
 [58  3]
 [59  3]
 [60  2]
 [61  2]
 [62  2]
 [63  3]
 [64  3]
 [65  3]
 [66  3]
 [67  3]
 [68  3]
 [69  3]
 [70  3]
 [71  3]
 [72  3]
 [73  2]
 [74  2]
 [75  3]
 [76  2]
 [77  3]
 [78  3]
 [79  2]
 [80  2]
 [81  3]
 [82  3]
 [83  3]
 [84  3]
 [85  3]
 [86  3]
 [87  3]
 [88  2]
 [89  3]
 [90  2]
 [91  3]
 [92  3]
 [93  3]
 [94  2]]


In [8]:
# each row of the Series object is an array. Classifiers won't read it. We create a matrix of values.
def from_series_to_matrix(num_predictors:int, time_series:pd.Series) -> np.ndarray:
    """Function used to transform the pandas Series to a matrix.
    Used to feed classifiers.

    Args:
        num_predictors (int): numbers of predictors
        time_series (pd.Series): time series data

    Returns:
        np.ndarray: NxM matrix where:
        - N is the number of examples
        - M is the number of predictors
    """
    a = np.zeros(shape=(len(time_series), num_predictors))
    for i in range(len(time_series)):
        for j in range(num_predictors):
            a[i,j] = time_series.iloc[i][j]
    return a

# compute_mean_feature_vector used to compute baseline
def compute_mean_feature_vector(time_series:pd.Series) -> np.ndarray:
    """Compute the mean of each field of each time series example

    Args:
        time_series (pd.Series): time series

    Returns:
        np.ndarray: feature vector for each entry
    """
    num_predictors = time_series.iloc[0].shape[-1]
    return from_series_to_matrix(num_predictors, time_series.apply(lambda x: np.mean(x, axis=0)))

X_train_mean_fv = compute_mean_feature_vector(X_train)
X_test_mean_fv = compute_mean_feature_vector(X_test)

In [9]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import StandardScaler

SC = StandardScaler()
SC.fit(X_train_mean_fv)
matrix_X_train_mean_fv_scaled = SC.transform(X_train_mean_fv)
matrix_X_test_mean_fv_scaled = SC.transform(X_test_mean_fv)



In [14]:
import itertools
from tqdm import tqdm
best_acc_score = 0
best_combination = ''
params = [['linear', 'poly', 'rbf', 'sigmoid'], [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 2, 5, 10], [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 2, 5, 10],[2, 3, 5, 6, 8, 9, 10]]
params_comb = list(itertools.product(*params))

for params in tqdm(params_comb, desc='calculating diff params combinations..'):
    svc = SVC(kernel=params[0], C=params[1], gamma = params[2], degree= params[3])
    svc.fit(matrix_X_train_mean_fv_scaled, y_train.values)
    predictions = svc.predict(matrix_X_test_mean_fv_scaled)
    res = accuracy_score(y_test.values, predictions)
    if res > best_acc_score:
        best_acc_score = res
        best_combination = f'kernel:{params[0]}, C={params[1]}, gamma={params[2]}, degree={params[3]}.'
        print(f'found new best acc score! {best_acc_score}, best combination: {best_combination}')
print(f'best accuracy score: {best_acc_score}, best combination: {best_combination}')


calculating diff params combinations..:   0%|          | 1/2268 [00:00<20:44,  1.82it/s]

found new best acc score! 0.14785992217898833, best combination: kernel:linear, C=1e-05, gamma=1e-05, degree=2.


calculating diff params combinations..:   8%|▊         | 190/2268 [01:53<17:38,  1.96it/s]

found new best acc score! 0.5953307392996109, best combination: kernel:linear, C=0.01, gamma=1e-05, degree=2.


calculating diff params combinations..:  11%|█         | 253/2268 [02:19<12:59,  2.59it/s]

found new best acc score! 0.8326848249027238, best combination: kernel:linear, C=0.1, gamma=1e-05, degree=2.


calculating diff params combinations..:  14%|█▍        | 316/2268 [02:41<11:18,  2.88it/s]

found new best acc score! 0.8560311284046692, best combination: kernel:linear, C=1, gamma=1e-05, degree=2.


calculating diff params combinations..: 100%|██████████| 2268/2268 [23:36<00:00,  1.60it/s]

best accuracy score: 0.8560311284046692, best combination: kernel:linear, C=1, gamma=1e-05, degree=2.


-------------

In [13]:
def compute_S_matrix(ts_series:pd.Series, means:np.array, vars:np.array) -> tuple:
    """function to compute the S matrix of shape n x N (n = number of predictors, N = number of examples). 
    Such matrix will be used to compute
    the weight vector needed by Eros norm

    Args:
        -ts_series (pd.Series): Series containing the dataset of time series.
        Each entry is a list of vectors. 
        Each vector is a component of the i-th time series
        -means (np.array): array containing the means of the features in order to scale them
        -vars (np.array): array containing the vars of the features in order to scale them

    Returns:
        tuple[np.array, list]: returns the matrix S and the list of
        right eigenvectors matrices computed for each time series
    """
    s_matrix = np.zeros(shape=(len(ts_series), ts_series.iloc[0].shape[-1]))
    v_list = [] # list of right eigenvector matrix
    for i in range(len(ts_series)):
        ts = ts_series.iloc[i] # time x predictors
        #The matrix S will be nxN where n is the predictor dimension and N is the number of time-series examples.
        #Hence, we will use the transpose to compute the covariance matrix.
        ts = (ts - means)/vars
        ts = ts.T # predictors x time
        #Compute the covariance matrix of the i-th example of the dataset
        #cov_ts = np.corrcoef(ts)
        cov_ts = np.cov(ts)
        # Compute the SVD of the covariance matrix
        u, s, v_t = np.linalg.svd(cov_ts)
        s_matrix[i] = s
        v_list.append(v_t.T)
    return s_matrix.T, v_list

In [14]:
X_train_matrix = np.vstack(X_train)
means_train = np.mean(X_train_matrix, axis=0)
vars_train = np.var(X_train_matrix, axis=0)

In [15]:
means_train, vars_train

(array([-0.05552374, -0.11289002, -0.13787006,  0.59797003,  0.30809794,
         0.46319201,  0.08904312,  0.05249049,  0.03018527,  0.05478745,
         0.0710108 ,  0.05099855, -0.04383498, -0.1204966 ,  0.43707669,
         0.39037003,  0.54879382,  0.28033495,  0.05691277,  0.22594754,
         0.13801296,  0.26404592]),
 array([0.00188294, 0.00639601, 0.00431505, 0.00793959, 0.01775536,
        0.00275456, 0.05224821, 0.02878818, 0.02108311, 0.03239591,
        0.03702743, 0.00397724, 0.01943236, 0.00798253, 0.00815517,
        0.02802097, 0.00769526, 0.13196413, 0.04176523, 0.12569881,
        0.0930127 , 0.12833541]))

In [16]:
S, v_list_train = compute_S_matrix(X_train, means_train, vars_train)

In [17]:
_, v_list_test = compute_S_matrix(X_test, means_train, vars_train)

In [18]:
def compute_weight_vector(S:np.ndarray, aggregation:str='mean', algorithm:int=1) -> np.array:
    """compute the weight vector used in the computation of Eros norm

    Args:
        S (np.ndarray): matrix containing eigenvalues of each predictor
        aggregation (str, optional): aggregation function to use. Defaults to 'mean'.
        algorithm(int): choose the algorithm to use to compute weight vector.
        - Algorithm 1: do not normalize rows of the S matrix. Perform directly the computation of w
        - Algorithm 2: first normalize rows of the S matrix and then compute w.
    Returns:
        np.array: return the normalized weight vector
    """
    n = S.shape[0] # number of predictors
    if (algorithm == 2):
        # first normalize each eigenvalues
        S = S/np.sum(S, axis=0)
    if (aggregation == 'mean'):
        w = np.mean(S, axis=-1)
    elif (aggregation == 'min'):
        w = np.min(S, axis=-1)
    elif (aggregation == 'max'):
        w = np.max(S, axis=-1)
    return w/np.sum(w)

In [19]:
w = compute_weight_vector(S, algorithm=2)


In [20]:
def eros_norm(weight_vector:np.array, A:np.array, B:np.array):
    """compute eros norm

    Args:
        weight_vector (np.array): weight vector
        A (np.array): time_series_1
        B (np.array): time_series_2

    Returns:
        float: distance between the 2 time series. Bounded in (0,1]
    """
    # since we want to use a_i and b_i which 
    # are the orthonormal column vectors of A and B,
    # we decide to transpose A and B
    A = A.T
    B = B.T
    n = A.shape[0] # number of predictors

    
    eros = 0
    
    for i in range(n):
        eros += weight_vector[i]*np.abs(np.dot(A[i], B[i]))
    return eros

def compute_kernel_matrix(num_examples:int, weight_vector:np.array, v_list:list) -> np.array:
    """compute the kernel matrix to be used in PCA

    Args:
        num_examples (int): number of examples in the dataset
        weight_vector (np.array): weight vector 
        v_t_list (list[np.array]): list of right eigenvector matrices

    Returns:
        np.array: kernel matrix with pairwise eros norm
    """
    N = num_examples
    K_eros = np.zeros(shape=(N,N))

    for i in range(N):
        j = 0
        while (j <= i):
            K_eros[i,j] = eros_norm(weight_vector, v_list[i], v_list[j])
            if (i != j): 
                K_eros[j,i] = K_eros[i,j]
            j += 1

    # check whether the kernel matrix is positive semi definite (PSD) or not
    is_psd = np.all(np.linalg.eigvals(K_eros) >= 0)
    #is_psd = True
    print(np.min(np.linalg.eigvals(K_eros)))
    threshold = 1e-10
    # if not PSD, add to the diagonal the minimal value among eigenvalues of K_eros
    if is_psd == False:
        delta = np.min(np.linalg.eigvals(K_eros))
        delta_ary = [np.abs(delta) + threshold for _ in range(K_eros.shape[0])]
        K_eros += np.diag(delta_ary)
    is_psd = np.all(np.linalg.eigvals(K_eros) >= 0)
    if is_psd == True:
        print("now PSD")
    else:
        print("not PSD")
    return K_eros

def perform_PCA(num_examples:int, weight_vector:np.array, v_list:list) -> tuple:
    """extract principal components in the feature space

    Args:
        num_examples (int): number of examples in the dataset
        weight_vector (np.array): weight vector 
        v_t_list (list[np.array]): list of right eigenvector matrices

    Returns:
        tuple[np.ndarray, np.array]:
        - K_eros matrix
        - eigenvectors (principal components) of the feature space
    """
    K_eros = compute_kernel_matrix(num_examples, weight_vector, v_list)
    O = np.ones(shape=(num_examples,num_examples))
    O *= 1/num_examples
    K_eros_mc = K_eros - O@K_eros - K_eros@O + O@K_eros@O # K_eros mean centered
    is_psd = np.all(np.linalg.eigvals(K_eros_mc) >= 0)
    print(f"K eros mean centered is {'not ' if not is_psd else ''}PSD")
    eig_vals, eig_vecs = np.linalg.eig(K_eros_mc)
    return K_eros, eig_vecs, eig_vals


def project_test_data(num_training_examples:int, num_test_examples:int, weight_vector:np.array, v_list_train:list, v_list_test:list, K_eros_train:np.ndarray, V:np.ndarray) -> tuple:
    """compute the K eros test kernel matrix used to project test data

    Args:
        num_examples_train (int): number of examples in the training dataset
        num_examples_test (int): number of examples in the test dataset
        weight_vector (np.array): weight vector 
        v_list_train (list[np.array]): list of right eigenvector matrices of the training dataset
        v_list_test (list[np.array]): list of right eigenvector matrices of the test dataset

    Returns:
        np.array: kernel matrix with pairwise eros norm
    """
    N_train = num_training_examples
    N_test = num_test_examples
    K_eros_test = np.zeros(shape=(N_test,N_train))

    for i in range(N_test):
        for j in range(N_train):
            K_eros_test[i,j] = eros_norm(weight_vector, v_list_test[i], v_list_train[j])
    
    O_test = np.ones(shape=(N_test, N_train))*(1/N_train)
    O_train = np.ones(shape=(N_train, N_train))*(1/N_train)

    K_eros_test_mc = K_eros_test - O_test@K_eros_train - K_eros_test@O_train + O_test@K_eros_train@O_train

    Y = K_eros_test_mc @ V
    
    return Y, K_eros_test

In [21]:
K_eros_train, V, eig_vals = perform_PCA(len(X_train), weight_vector=w, v_list=v_list_train)

-27.709595645972787
now PSD
K eros mean centered is PSD


In [22]:
Y, K_eros_test = project_test_data(len(X_train), len(X_test), w, v_list_train, v_list_test, K_eros_train, V)

In [23]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components=None, kernel='precomputed')
principal_comps_train = kpca.fit_transform(K_eros_train)
principal_comps_test = kpca.transform(K_eros_test)



In [24]:
V.shape, Y.shape, principal_comps_train.shape, principal_comps_test.shape

((2308, 2308), (257, 2308), (2308, 2307), (257, 2307))

In [24]:
###BASIC param search on our version of KPCA with eros
import itertools
from tqdm import tqdm
best_acc_score = 0
best_combination = ''
params = [['linear', 'poly', 'rbf', 'sigmoid'], [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 2, 5, 10], [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 2, 5, 10],[15,16, 17, 20, 22, 23, 24, 25, 26, 27, 28, 30]]
params_comb = list(itertools.product(*params))
for params in tqdm(params_comb, desc='calculating diff params combinations..'):
    svc = SVC(kernel=params[0], C=params[1], gamma = params[2], degree= params[3])
    princ_components = V[:, :51]
    svc.fit(princ_components, y_train.values)
    test_princ_components = Y[:, :51]
    predictions = svc.predict(test_princ_components)
    res = accuracy_score(y_test.values, predictions)
    if res > best_acc_score:
        best_acc_score = res
        best_combination = f'kernel:{params[0]}, C={params[1]}, gamma={params[2]}, degree={params[3]}.'
        print(f'found new best acc score! {best_acc_score}, best combination: {best_combination}')
print(f'best accuracy score: {best_acc_score}, best combination: {best_combination}')

calculating diff params combinations..:   0%|          | 1/3888 [00:00<45:51,  1.41it/s]

found new best acc score! 0.19066147859922178, best combination: kernel:linear, C=1e-05, gamma=1e-05, degree=15.


calculating diff params combinations..:  11%|█         | 433/3888 [05:23<38:14,  1.51it/s]  

found new best acc score! 0.2140077821011673, best combination: kernel:linear, C=0.1, gamma=1e-05, degree=15.


calculating diff params combinations..:  14%|█▍        | 541/3888 [06:32<38:50,  1.44it/s]

found new best acc score! 0.6653696498054474, best combination: kernel:linear, C=1, gamma=1e-05, degree=15.


calculating diff params combinations..:  17%|█▋        | 649/3888 [07:46<33:01,  1.63it/s]

found new best acc score! 0.7003891050583657, best combination: kernel:linear, C=2, gamma=1e-05, degree=15.


calculating diff params combinations..:  27%|██▋       | 1057/3888 [11:56<35:36,  1.33it/s]

found new best acc score! 0.7859922178988327, best combination: kernel:poly, C=1e-05, gamma=5, degree=15.


calculating diff params combinations..:  27%|██▋       | 1058/3888 [11:57<34:45,  1.36it/s]

found new best acc score! 0.7976653696498055, best combination: kernel:poly, C=1e-05, gamma=5, degree=16.


calculating diff params combinations..:  27%|██▋       | 1060/3888 [11:58<34:05,  1.38it/s]

found new best acc score! 0.8093385214007782, best combination: kernel:poly, C=1e-05, gamma=5, degree=20.


calculating diff params combinations..:  27%|██▋       | 1061/3888 [11:59<33:42,  1.40it/s]

found new best acc score! 0.8132295719844358, best combination: kernel:poly, C=1e-05, gamma=5, degree=22.


calculating diff params combinations..:  27%|██▋       | 1062/3888 [12:00<34:03,  1.38it/s]

found new best acc score! 0.8171206225680934, best combination: kernel:poly, C=1e-05, gamma=5, degree=23.


calculating diff params combinations..:  31%|███       | 1188/3888 [13:41<45:53,  1.02s/it]  

found new best acc score! 0.8210116731517509, best combination: kernel:poly, C=0.0001, gamma=10, degree=30.


calculating diff params combinations..: 100%|██████████| 3888/3888 [53:07<00:00,  1.22it/s]

best accuracy score: 0.8210116731517509, best combination: kernel:poly, C=0.0001, gamma=10, degree=30.


In [25]:
###DEEPER param search on our version of KPCA with eros (on poly kernel)

best_acc_score = 0
best_combination = ''
params = [['poly'], [0.00001, 0.0005, 0.0001, 0.0005, 0.001, 0.005], [5,8, 9, 10,11,12,13,15,20],[25, 27, 28, 29, 30,31,32,33,35,40]]
params_comb = list(itertools.product(*params))
for params in tqdm(params_comb, desc='calculating diff params combinations..'):
    svc = SVC(kernel=params[0], C=params[1], gamma = params[2], degree= params[3])
    princ_components = V[:, :51]
    svc.fit(princ_components, y_train.values)
    test_princ_components = Y[:, :51]
    predictions = svc.predict(test_princ_components)
    res = accuracy_score(y_test.values, predictions)
    if res > best_acc_score:
        best_acc_score = res
        best_combination = f'kernel:{params[0]}, C={params[1]}, gamma={params[2]}, degree={params[3]}.'
        print(f'found new best acc score! {best_acc_score}, best combination: {best_combination}')
print(f'best accuracy score: {best_acc_score}, best combination: {best_combination}')

calculating diff params combinations..:   0%|          | 1/540 [00:01<11:35,  1.29s/it]

found new best acc score! 0.8132295719844358, best combination: kernel:poly, C=1e-05, gamma=5, degree=25.


calculating diff params combinations..:   1%|          | 4/540 [00:03<06:53,  1.30it/s]

found new best acc score! 0.8171206225680934, best combination: kernel:poly, C=1e-05, gamma=5, degree=29.


calculating diff params combinations..:   1%|          | 6/540 [00:04<06:35,  1.35it/s]

found new best acc score! 0.8210116731517509, best combination: kernel:poly, C=1e-05, gamma=5, degree=31.


calculating diff params combinations..:   9%|▊         | 46/540 [00:32<05:30,  1.50it/s]

found new best acc score! 0.8249027237354085, best combination: kernel:poly, C=1e-05, gamma=11, degree=31.


calculating diff params combinations..: 100%|██████████| 540/540 [06:19<00:00,  1.42it/s]

best accuracy score: 0.8249027237354085, best combination: kernel:poly, C=1e-05, gamma=11, degree=31.


In [25]:
#BASIC params search on sklearn KPCA with our kernel (not centered).
import itertools
from tqdm import tqdm
best_acc_score = 0
best_combination = ''
params = [['linear', 'poly', 'rbf', 'sigmoid'], [0.00001, 0.0005, 0.0001, 0.0005, 0.001, 0.005], [5,8, 9, 10,11,12,13,15,20],[25, 27, 28, 29, 30,31,32,33,35,40]]
params_comb = list(itertools.product(*params))
for params in tqdm(params_comb, desc='calculating diff params combinations..'):
    svc = SVC(kernel=params[0], C=params[1], gamma = params[2], degree= params[3])
    svc.fit(principal_comps_train[:,:51], y_train.values)
    predictions = svc.predict(principal_comps_test[:,:51])
    res = accuracy_score(y_test.values, predictions)
    if res > best_acc_score:
        best_acc_score = res
        best_combination = f'kernel:{params[0]}, C={params[1]}, gamma={params[2]}, degree={params[3]}.'
        print(f'found new best acc score! {best_acc_score}, best combination: {best_combination}')
print(f'best accuracy score: {best_acc_score}, best combination: {best_combination}')

calculating diff params combinations..:   0%|          | 1/2160 [00:00<23:45,  1.51it/s]

found new best acc score! 0.19455252918287938, best combination: kernel:linear, C=1e-05, gamma=5, degree=25.


calculating diff params combinations..:  25%|██▌       | 548/2160 [06:37<25:46,  1.04it/s]

In [ ]:
#again KernelPCA but with centered kernel.
num_examples_train = K_eros_train.shape[0]
num_examples_test = K_eros_test.shape[0]
O = np.ones(shape=(num_examples_train,num_examples_train))
O *= 1/num_examples_train
K_eros_mc_train = K_eros_train - O@K_eros_train - K_eros_train@O + O@K_eros_train@O
O_test = np.ones(shape=(num_examples_test, num_examples_train))*(1/num_examples_train)
K_eros_mc_test = K_eros_test - O_test@K_eros_train - K_eros_test@O + O_test@K_eros_train@O
kpca = KernelPCA(n_components=None, kernel='precomputed')
principal_comps_train = kpca.fit_transform(K_eros_mc_train)
principal_comps_test = kpca.transform(K_eros_mc_test)

In [ ]:
#BASIC params search on sklearn KPCA with our kernel (centered).

best_acc_score = 0
best_combination = ''
params = [['linear', 'poly', 'rbf', 'sigmoid'], [0.00001, 0.0005, 0.0001, 0.0005, 0.001, 0.005], [5,8, 9, 10,11,12,13,15,20],[25, 27, 28, 29, 30,31,32,33,35,40]]
params_comb = list(itertools.product(*params))
for params in tqdm(params_comb, desc='calculating diff params combinations..'):
    svc = SVC(kernel=params[0], C=params[1], gamma = params[2], degree= params[3])
    svc.fit(principal_comps_train[:,:51], y_train.values)
    predictions = svc.predict(principal_comps_test[:,:51])
    res = accuracy_score(y_test.values, predictions)
    if res > best_acc_score:
        best_acc_score = res
        best_combination = f'kernel:{params[0]}, C={params[1]}, gamma={params[2]}, degree={params[3]}.'
        print(f'found new best acc score! {best_acc_score}, best combination: {best_combination}')
print(f'best accuracy score: {best_acc_score}, best combination: {best_combination}')

-----------------------------------------------------------------------------------------------------------------

In [7]:
#interpolate the dataframe
def interpolate_time_series(x:np.ndarray, n_new_coords:int)->np.ndarray:
    n_old_coords, n_predictors = x.shape
    x_new = np.zeros((n_new_coords, n_predictors))
    for i in range(n_predictors):
        x_new[:, i] = np.interp(np.linspace(0, n_old_coords, num=n_new_coords), np.array(list(range(n_old_coords))), x[:, i])
    return x_new

def interpolate_data(X:pd.Series, n_new_coords:int)->pd.Series:
    n_examples = len(X)
    X_new = X.apply(lambda x : interpolate_time_series(x, n_new_coords))
    return X_new

In [33]:
n_coords = 60
X_train_interp, X_test_interp = interpolate_data(X_train, n_coords), interpolate_data(X_test, n_coords)

In [34]:
print(X_train_interp.iloc[0].shape, X_train.iloc[0].shape)

(60, 22) (56, 22)


In [44]:
def concatenate_examples(X:pd.Series)->np.ndarray:
    new_x = np.zeros((len(X), (X.iloc[0].shape[1]*n_coords)))
    for i in range(len(X)):
        new_x[i] = X.iloc[i].flatten()
    return new_x

In [45]:
X_train_interp.iloc[0].shape[1]

22

In [46]:
X_train_interp = concatenate_examples(X_train_interp)
X_test_interp = concatenate_examples(X_test_interp)

In [49]:
X_train_interp[0].shape, 60*22

((1320,), 1320)

In [54]:
from sklearn.preprocessing import StandardScaler

SC = StandardScaler()
SC.fit(X_train_interp)
X_train_interp = SC.transform(X_train_interp)
X_test_interp = SC.transform(X_test_interp)

In [55]:
#perform Linear Kernel PCA on the interpolated dataset
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components=None, kernel='linear')

principal_comps_train = kpca.fit_transform(X_train_interp)
principal_comps_test = kpca.transform(X_test_interp)

In [57]:
principal_comps_train.shape, principal_comps_test.shape

((2308, 1225), (257, 1225))

In [58]:
explained_variance = np.var(principal_comps_train, axis=0)
explained_variance_ratio = explained_variance / np.sum(explained_variance)

In [63]:
np.sum(explained_variance_ratio[:51])

0.9459232836823346

In [64]:
#BASIC params search on Linear KPCA.
import itertools
from tqdm import tqdm
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
best_acc_score = 0
best_combination = ''
params = [['linear', 'poly', 'rbf', 'sigmoid'], [0.00001, 0.0005, 0.0001, 0.0005, 0.001, 0.005], [5,8, 9, 10,11,12,13,15,20],[25, 27, 28, 29, 30,31,32,33,35,40]]
params_comb = list(itertools.product(*params))
for params in tqdm(params_comb, desc='calculating diff params combinations..'):
    svc = SVC(kernel=params[0], C=params[1], gamma = params[2], degree= params[3])
    svc.fit(principal_comps_train[:,:51], y_train.values)
    predictions = svc.predict(principal_comps_test[:,:51])
    res = accuracy_score(y_test.values, predictions)
    if res > best_acc_score:
        best_acc_score = res
        best_combination = f'kernel:{params[0]}, C={params[1]}, gamma={params[2]}, degree={params[3]}.'
        print(f'found new best acc score! {best_acc_score}, best combination: {best_combination}')
print(f'best accuracy score: {best_acc_score}, best combination: {best_combination}')

calculating diff params combinations..:   0%|          | 1/2160 [00:00<24:53,  1.45it/s]

found new best acc score! 0.16342412451361868, best combination: kernel:linear, C=1e-05, gamma=5, degree=25.


calculating diff params combinations..:   4%|▍         | 91/2160 [00:57<19:53,  1.73it/s]

found new best acc score! 0.8015564202334631, best combination: kernel:linear, C=0.0005, gamma=5, degree=25.


calculating diff params combinations..:  17%|█▋        | 361/2160 [03:54<17:44,  1.69it/s]  

found new best acc score! 0.8988326848249028, best combination: kernel:linear, C=0.001, gamma=5, degree=25.


calculating diff params combinations..:  21%|██        | 451/2160 [04:46<15:54,  1.79it/s]

found new best acc score! 0.9416342412451362, best combination: kernel:linear, C=0.005, gamma=5, degree=25.


calculating diff params combinations..: 100%|██████████| 2160/2160 [28:29<00:00,  1.26it/s]

best accuracy score: 0.9416342412451362, best combination: kernel:linear, C=0.005, gamma=5, degree=25.
